<?php

/**
 * @file
 * Defines a simple string formatter.
 */

use Drupal\Core\Field\FieldTypeCategoryManagerInterface;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_field_formatter_info_alter().
 */
function nearby_transport_formatter_field_formatter_info_alter(&$info) {
  $info['string']['field_types'][] = 'geofield';
}

/**
 * Implements hook_theme().
 */
function nearby_transport_formatter_theme($existing, $type, $theme, $path) {
  return [
    'nearby_stations' => [
      'variables' => [
        'lat' => NULL,
        'lon' => NULL,
        'metros' => [],
        'trains' => [],
        'bus_longs' => [],
        'bus_shorts' => [],
        'ferries' => [],
        'lovelos' => [],
        'bike_locks' => [],
        'max_distance' => 500,
        'map' => [],
      ],
    ],
    'nearby_routes' => [
      'variables' => [
        'routes' => [],
      ],
    ],
    'nearby_cycle' => [
      'variables' => [
        'station_name' => '',
        'free' => '',
        'distance' => '',
        'direction' => '',
        'lat' => '',
        'lon' => '',
        'capacity' => '',
      ],
    ],
    'nearby_locks' => [
      'variables' => [
        'locks' => [],
      ],
    ],
    'nearby_lock' => [
      'variables' => [
        'category_name' => '',
        'distance' => '',
        'direction' => '',
        'lat' => '',
        'lon' => '',
        'capacity' => '',
      ],
    ],
  ];
}
